service: yoyoplentyserverless-nodejs-app

custom: # add these two lines
  secrets: ${file(secrets.json)} # reference the secrets.json file
  # serverless-offline-watcher:
  #   - path: .
  #     command: echo "index.ts was modified!" && kill -9 $(lsof -t -i:3000) && yarn start:dev

provider:
  name: aws
  runtime: nodejs18.x
  # stage: production # make sure to change this to production
  region: us-east-1
  environment: # add environment property
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    MONGO_URI: ${self:custom.secrets.MONGO_URI}
    # reference the NODE_ENV from the secrets.json file

  timeout: 600

plugins:
  - serverless-offline
  - serverless-offline-watcher

package:
  exclude:
    # - node_modules/**
    - test.secrets.json
    - prod.secrets.json
    - .env
    - src

functions:
  serverless:
    handler: dist/serverless.handler
    events:
      - http:
          path: graphql
          method: get
          cors: true
